include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
  exclude:
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "lib/gen/lib/model/*.dart"

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true
    prefer_single_quotes: true